[project]
name = 'Seed-Bank-and-Biodiversity-Preservation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.growth-tracker]
path = 'contracts/growth-tracker.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
